export enum EmailDeliveryStatus {
  BOUNCED = 'BOUNCED',
  COMPLAINED = 'COMPLAINED',
  DELIVERED = 'DELIVERED',
  DELIVERY_DELAYED = 'DELIVERY_DELAYED',
  FAILED = 'FAILED',
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  SUPPRESSED = 'SUPPRESSED',
}
